version: "3.8"

networks:
    app-tier:
        driver: bridge
services:
  backend:
    container_name: loja_backend
    depends_on:
      db:
        condition: service_started
    restart: on-failure  
    build:
      context: ./backend
    ports:
      - 3333:3333
    volumes:
      - ./backend:/usr/src/app/backend
    env_file: ./backend/.env

  frontend:
    container_name: loja_frontend
    depends_on:
      backend:
        condition: service_started
    restart: on-failure
    build:
      context: ./frontend
    ports:
      - 3366:3366
    volumes:
      - ./frontend:/usr/src/app/frontend
  db:
    image: mysql:8.0
    container_name: loja_db_test
    security_opt:
      - seccomp:unconfined
    ports:
      - 3320:3306
    environment:
      - MYSQL_DATABASE=lojavirtual
      - MYSQL_ROOT_PASSWORD=123456
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8010:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql_db:
  mysql_db_config:
  mysql_test:
  mysql_config_test:
